export SPHENO_ROOT=`pwd`
export PYTHONPATH="$PYTHONPATH:$SPHENO_ROOT/python"
export SPHENO_PATH="$SPHENO_ROOT/SPheno"
export PATH="$PATH:$SPHENO_PATH/bin"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$SPHENO_PATH/lib"
